name: julia-lang
#base: core18 # the base snap is the execution environment for this snap
version: '1.0.3'
summary: The Julia Programming Language
description: |
  Julia is a high-level general-purpose dynamic programming language that was
  originally designed to address the needs of high-performance numerical
  analysis and computational science, without the typical need of separate
  compilation to be fast, also usable for client and server web use,
  low-level systems programming or as a specification language.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures: [amd64, i386, arm64, armhf]

apps:
  julia:
    command: bin/julia

parts:
  julia:
    plugin: dump
    source-type: tar
    #source-checksum: add as soon as snapcraft understands advanced grammer for this field to match the architecture
    source:
      - to amd64: https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-$SNAPCRAFT_PROJECT_VERSION-linux-x86_64.tar.gz
      - to i386: https://julialang-s3.julialang.org/bin/linux/x86/1.0/julia-$SNAPCRAFT_PROJECT_VERSION-linux-i686.tar.gz
      - to arm64: https://julialang-s3.julialang.org/bin/linux/aarch64/1.0/julia-$SNAPCRAFT_PROJECT_VERSION-linux-aarch64.tar.gz
      - to armhf: https://julialang-s3.julialang.org/bin/linux/armv7l/1.0/julia-$SNAPCRAFT_PROJECT_VERSION-linux-armv7l.tar.gz
